set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property PACKAGE_PIN V17 [get_ports sw1]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN K16 [get_ports rstn]
set_property PACKAGE_PIN M15 [get_ports {led[0]}]
set_property PACKAGE_PIN M14 [get_ports {led[1]}]
set_property PACKAGE_PIN J16 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
