# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/fifo_8b_2_32b_1/fifo_8b_2_32b.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_8b_2_32b || ORIG_REF_NAME==fifo_8b_2_32b} -quiet] -quiet
