# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo.xci
# IP: The module: 'r2u_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo.xci
# IP: The module: 'r2u_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86157/Desktop/PC_Cotroller/PC_Cotroller.srcs/sources_1/ip/r2u_data_fifo_1/r2u_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r2u_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
