@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 15 23:57:47 +0800 2024
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim FSM_test_behav -key {Behavioral:sim_1:Functional:FSM_test} -tclbatch FSM_test.tcl -view C:/Users/86157/Desktop/计组实验/FSM/FSM_behav.wcfg -log simulate.log"
call xsim  FSM_test_behav -key {Behavioral:sim_1:Functional:FSM_test} -tclbatch FSM_test.tcl -view C:/Users/86157/Desktop/计组实验/FSM/FSM_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
